[build]
  command = "npm run build"
  publish = "_site"

# Exclude asset paths
[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

[[redirects]]
  from = "/scripts/*"
  to = "/scripts/:splat"
  status = 200

[[redirects]]
  from = "/styles/*"
  to = "/styles/:splat"
  status = 200

[[redirects]]
  from = "/data/*"
  to = "/data/:splat"
  status = 200

# Legacy .html to clean folder structure
[[redirects]]
  from = "/blog/*.html"
  to = "/blog/:splat/"
  status = 301
  force = true

# Catch-all
[[redirects]]
  from = "/*"
  to = "/:splat/"
  status = 301
